version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Build completed on `date`
  post_build:
    commands:
      - aws s3 sync . s3://csce412ool.xyz --region us-east-2 --delete
artifacts:
  files:
    - '**/*'
